### ISSUE TITLE
Continuation of distributed study from pickled study

### ISSUE THREAD

**Issue by Raverss** [xadrianzetx/optuna-distributed#75]
**Describe the bug**
Continuing optimization from pickled distributed study with multiple objectives raises error.

**To Reproduce**
1. Define multi-objective function
2. Create distributed study with n_jobs > 1
3. Save it to pickle using joblib
4. Load it using joblib
5. Create distributed study from the loaded pickled study
6. Call optimize again with n_jobs > 1
7. get error

**Expected behavior**
Expected behavior is continuation of study.

**Additional context**
Error looks like this:
```
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/bot/lib/python3.10/site-packages/optuna_distributed/eventloop.py", line 65, in run
    message.process(self.study, self.manager)
  File "/home/user/miniconda3/envs/bot/lib/python3.10/site-packages/optuna_distributed/messages/suggest.py", line 44, in process
    trial = Trial(study, self._trial_id)
  File "/home/user/miniconda3/envs/bot/lib/python3.10/site-packages/optuna/trial/_trial.py", line 53, in __init__
    self._study_id = self.study._study_id
AttributeError: 'DistributedStudy' object has no attribute '_study_id'. Did you mean: '_study'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/miniconda3/envs/bot/lib/python3.10/site-packages/optuna_distributed/study.py", line 192, in optimize
    event_loop.run(terminal, timeout, catch)
  File "/home/user/miniconda3/envs/bot/lib/python3.10/site-packages/optuna_distributed/eventloop.py", line 72, in run
    self._fail_unfinished_trials()
  File "/home/user/miniconda3/envs/bot/lib/python3.10/site-packages/optuna_distributed/eventloop.py", line 94, in _fail_unfinished_trials
    self.study._storage.set_trial_state_values(trial._trial_id, TrialState.FAIL)
AttributeError: 'DistributedStudy' object has no attribute '_storage'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/repos/private/project/optimize_simulation.py", line 178, in <module>
    study.optimize(objective, n_trials=args.trials, n_jobs=args.n_jobs)
  File "/home/user/miniconda3/envs/bot/lib/python3.10/site-packages/optuna_distributed/study.py", line 205, in optimize
    self._study._storage.remove_session()
AttributeError: 'DistributedStudy' object has no attribute '_storage'
```
I'm on Ubuntu.

**Comment by xadrianzetx** [comment]
Thanks for reporting this! Could you share a reproducible example?

**Comment by Raverss** [comment]
I found the mistake, it was on my end. Sorry to take your time. The mistake was creating another distributed study from the loaded study. The loaded study was already distributed study and therefore from_study function failed.
For the reference:

```
import joblib  # type: ignore
import optuna as opt  # type: ignore
import optuna_distributed as opt_dst


def objective(trial: opt.trial.Trial):
    x = trial.suggest_int('x', 0, 1000)
    return x*x, x


study = opt.create_study(directions=["maximize", "maximize"], sampler=opt.samplers.TPESampler())
study = opt_dst.from_study(study)
study.optimize(objective, n_trials=4, n_jobs=2)
joblib.dump(study, "study.pkl")

study = joblib.load("study.pkl")
# study = opt_dst.from_study(study)
study.optimize(objective, n_trials=4, n_jobs=2)
```

this works. With the commented out line it raise the exception.

Thank you for the awesome library. You have saved me a lot of time <3
