### ISSUE TITLE
Multiprocessing with multiple GPUs

### ISSUE THREAD

**Issue by ggoupy** [xadrianzetx/optuna-distributed#92]
Hello. 

I have a server with 4 GPU devices.

Is there a way to easily instruct each process to use a distinct GPU ?

I have done something like (assuming the number of processes = the number of GPUs):
```python3
def objective(trial, ...):

    # Set device
    process_id = multiprocessing.current_process()._identity[0] - 1 
    num_gpus = cp.cuda.runtime.getDeviceCount() 
    gpu_device = process_id % num_gpus
    cp.cuda.Device(gpu_device).use()
``` 
However, I get an error: `cupy_backends.cuda.api.runtime.CUDARuntimeError: cudaErrorInitializationError: initialization error`.

Then I tried to add ```multiprocessing.set_start_method('spawn')``` at the beginning of my code but I get:
```
Traceback (most recent call last):
  File "/home/gagoupy/SNN/spikenn/app/hpo-multi.py", line 162, in <module>
    study.optimize(
  File "/home/gagoupy/.local/lib/python3.9/site-packages/optuna_distributed/study.py", line 192, in optimize
    event_loop.run(terminal, timeout, catch)
  File "/home/gagoupy/.local/lib/python3.9/site-packages/optuna_distributed/eventloop.py", line 61, in run
    self.manager.create_futures(self.study, self.objective)
  File "/home/gagoupy/.local/lib/python3.9/site-packages/optuna_distributed/managers/local.py", line 62, in create_futures
    p.start()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.9/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/usr/lib/python3.9/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function <lambda> at 0x7fe188c02670>: attribute lookup <lambda> on __main__ failed
```

Thanks :)

**Comment by xadrianzetx** [comment]
Hi,

 I think this question would be better suited for CuPy maintainers, as `optuna-distributed` has no control over the code executed within your objective function nor it should be a factor, maybe apart from the fact your objective is running in a forked process.

Guess your best bet is to try running the snippet you provided without multiprocessing first, then in a process created with `multiprocessing.Process` and looking for answers from there. Unfortunately, I'm not familiar enough with CuPy to help you further. If you find a solution using this toy setup, I'm sure you will be able to just use it in your objective function with distributed.

Also, `optuna-distributed` works by forking the process, so you shouldn't change the way to start a process.

**Comment by ggoupy** [comment]
> optuna-distributed has no control over the code executed within your objective function nor it should be a factor

Yeah that's what I thought but I am not familiar at all with multiprocessing. 

Alright, thanks for the suggestions !
