### ISSUE TITLE
An error occurs when running code on Windows 11.

### ISSUE THREAD

**Issue by thegreatesthoneybee** [xadrianzetx/optuna-distributed#94]
```
import random
import time

import optuna
import optuna_distributed
from dask.distributed import Client


def objective(trial):
    x = trial.suggest_float("x", -100, 100)
    y = trial.suggest_categorical("y", [-1, 0, 1])
    # Some expensive model fit happens here...
    time.sleep(random.uniform(1.0, 2.0))
    return x**2 + y


if __name__ == "__main__":
    # client = Client("<your.cluster.scheduler.address>")  # Enables distributed optimization.
    client = None  # Enables local asynchronous optimization.
    study = optuna_distributed.from_study(optuna.create_study(), client=client)
    study.optimize(objective, n_trials=10)
    print(study.best_value)
```
The above code works fine on my OS X system.
But I ran it on Windows 11 and got the error below.

> Traceback (most recent call last):
>   File "D:\SynologyDrive\Project\dask_test\dask_test.py", line 21, in <module>
>     study.optimize(objective, n_trials=10)
>   File "C:\miniconda3\envs\test\Lib\site-packages\optuna_distributed\study.py", line 185, in optimize
>     raise ValueError(
> ValueError: Local asynchronous optimization is currently not supported on Windows. Please specify Dask client to continue in distributed mode.

```
client = Client("127.0.0.1:8786")  # Enables distributed optimization.
# client = None  # Enables local asynchronous optimization.
```
When I modified the client part of the code as above, I got the following error

```
Traceback (most recent call last):
  File "D:\SynologyDrive\Project\dask_test\dask_test.py", line 18, in <module>
    client = Client("127.0.0.1:8786")  # Enables distributed optimization.
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniconda3\envs\test\Lib\site-packages\distributed\client.py", line 1224, in __init__
    self.start(timeout=timeout)
  File "C:\miniconda3\envs\test\Lib\site-packages\distributed\client.py", line 1426, in start
    sync(self.loop, self._start, **kwargs)
  File "C:\miniconda3\envs\test\Lib\site-packages\distributed\utils.py", line 440, in sync
    raise error
  File "C:\miniconda3\envs\test\Lib\site-packages\distributed\utils.py", line 414, in f
    result = yield future
             ^^^^^^^^^^^^
  File "C:\miniconda3\envs\test\Lib\site-packages\tornado\gen.py", line 766, in run
    value = future.result()
            ^^^^^^^^^^^^^^^
  File "C:\miniconda3\envs\test\Lib\site-packages\distributed\client.py", line 1505, in _start
    await self._ensure_connected(timeout=timeout)
  File "C:\miniconda3\envs\test\Lib\site-packages\distributed\client.py", line 1573, in _ensure_connected
    comm = await connect(
           ^^^^^^^^^^^^^^
  File "C:\miniconda3\envs\test\Lib\site-packages\distributed\comm\core.py", line 368, in connect
    raise OSError(
OSError: Timed out trying to connect to tcp://127.0.0.1:8786 after 30 s
```

Below is a list of libraries installed in my virtual environment.

```
# packages in environment at C:\miniconda3\envs\test:
#
# Name                    Version                   Build  Channel
alembic                   1.13.3             pyhd8ed1ab_0    conda-forge
arrow-cpp                 16.1.0               h7cd61ee_0
aws-c-auth                0.6.19               h2bbff1b_0
aws-c-cal                 0.5.20               h2bbff1b_0
aws-c-common              0.8.5                h2bbff1b_0
aws-c-compression         0.2.16               h2bbff1b_0
aws-c-event-stream        0.2.15               hd77b12b_0
aws-c-http                0.6.25               h2bbff1b_0
aws-c-io                  0.13.10              h2bbff1b_0
aws-c-mqtt                0.7.13               h2bbff1b_0
aws-c-s3                  0.1.51               h2bbff1b_0
aws-c-sdkutils            0.1.6                h2bbff1b_0
aws-checksums             0.1.13               h2bbff1b_0
aws-crt-cpp               0.18.16              hd77b12b_0
aws-sdk-cpp               1.10.55              hd77b12b_0
blas                      1.0                         mkl
bokeh                     3.6.0           py312haa95532_0
boost-cpp                 1.82.0               h59b6b97_2
bottleneck                1.3.7           py312he558020_0
brotli-python             1.0.9           py312hd77b12b_8
bzip2                     1.0.8                h2bbff1b_6
c-ares                    1.19.1               h2bbff1b_0
ca-certificates           2024.9.24            haa95532_0
click                     8.1.7           py312haa95532_0
cloudpickle               3.1.0                    pypi_0    pypi
colorama                  0.4.6           py312haa95532_0
colorlog                  6.8.2                    pypi_0    pypi
contourpy                 1.2.0           py312h59b6b97_0
cytoolz                   0.12.2          py312h2bbff1b_0
daal                      2024.7.0                 pypi_0    pypi
daal4py                   2024.7.0                 pypi_0    pypi
dask                      2024.10.0                pypi_0    pypi
dask-expr                 1.1.13          py312haa95532_0
distributed               2024.10.0                pypi_0    pypi
expat                     2.6.3                h5da7b33_0
freetype                  2.12.1               ha860e81_0
fsspec                    2024.9.0                 pypi_0    pypi
gflags                    2.2.2                hd77b12b_1
glog                      0.5.0                hd77b12b_1
greenlet                  3.1.1                    pypi_0    pypi
heapdict                  1.0.1              pyhd3eb1b0_0
importlib-metadata        8.5.0              pyha770c72_0    conda-forge
importlib_resources       6.4.5              pyhd8ed1ab_0    conda-forge
intel-openmp              2023.2.0         h57928b3_50497    conda-forge
jinja2                    3.1.4           py312haa95532_0
joblib                    1.4.2                    pypi_0    pypi
jpeg                      9e                   h827c3e9_3
lcms2                     2.12                 h83e58a3_0
lerc                      3.0                  hd77b12b_0
libabseil                 20240116.2      cxx17_h5da7b33_0
libboost                  1.82.0               h3399ecb_2
libbrotlicommon           1.0.9                h2bbff1b_8
libbrotlidec              1.0.9                h2bbff1b_8
libbrotlienc              1.0.9                h2bbff1b_8
libcurl                   8.9.1                h0416ee5_0
libdeflate                1.17                 h2bbff1b_1
libevent                  2.1.12               h56d1f94_1
libffi                    3.4.4                hd77b12b_1
libgrpc                   1.62.2               hf25190f_0
libhwloc                  2.11.1          default_h8125262_1000    conda-forge
libiconv                  1.17                 hcfcfb64_2    conda-forge
libpng                    1.6.39               h8cc25b3_0
libprotobuf               4.25.3               hf2fb9eb_0
libssh2                   1.11.0               h291bd65_0
libthrift                 0.15.0               h4364b78_2
libtiff                   4.5.1                hd77b12b_0
libwebp-base              1.3.2                h3d04722_1
libxml2                   2.13.1               h24da03e_2
locket                    1.0.0           py312haa95532_0
lz4                       4.3.2           py312h2bbff1b_0
lz4-c                     1.9.4                h2bbff1b_1
mako                      1.3.5              pyhd8ed1ab_0    conda-forge
markdown-it-py            3.0.0                    pypi_0    pypi
markupsafe                3.0.2                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
mkl                       2023.2.0         h6a75c08_50497    conda-forge
mkl-service               2.4.0           py312h2bbff1b_1
mkl_fft                   1.3.10          py312h827c3e9_0
mkl_random                1.2.7           py312h0158946_0
msgpack                   1.1.0                    pypi_0    pypi
numexpr                   2.8.7           py312h96b7d27_0
numpy                     2.0.0rc2                 pypi_0    pypi
numpy-base                1.26.4          py312h4dde369_0
openjpeg                  2.5.2                hae555c5_0
openssl                   3.3.2                h2466b09_0    conda-forge
optuna                    4.0.0              pyhd8ed1ab_0    conda-forge
optuna-distributed        0.7.0                    pypi_0    pypi
optuna-integration        4.0.0                    pypi_0    pypi
orc                       2.0.1                hd8d391b_0
packaging                 24.1            py312haa95532_0
pandas                    2.2.2           py312h0158946_0
partd                     1.4.2                    pypi_0    pypi
pillow                    10.4.0          py312h827c3e9_0
pip                       24.2            py312haa95532_0
psutil                    6.1.0                    pypi_0    pypi
pthreads-win32            2.9.1                h2466b09_4    conda-forge
pyarrow                   16.1.0          py312h0158946_0
pygments                  2.18.0                   pypi_0    pypi
pysocks                   1.7.1           py312haa95532_0
python                    3.12.3               h1d929f7_1
python-dateutil           2.9.0post0      py312haa95532_2
python-lmdb               1.4.1           py312hd77b12b_0
python-tzdata             2023.3             pyhd3eb1b0_0
pytz                      2024.1          py312haa95532_0
pyyaml                    6.0.2           py312h827c3e9_0
re2                       2022.04.01           hd77b12b_0
rich                      13.9.2                   pypi_0    pypi
scikit-learn              1.5.0                    pypi_0    pypi
scikit-learn-intelex      2024.7.0                 pypi_0    pypi
scipy                     1.14.0rc1                pypi_0    pypi
setuptools                75.1.0          py312haa95532_0
six                       1.16.0             pyhd3eb1b0_1
snappy                    1.2.1                hcdb6601_0
sortedcontainers          2.4.0              pyhd3eb1b0_0
sqlalchemy                2.0.36                   pypi_0    pypi
sqlite                    3.45.3               h2bbff1b_0
tbb                       2021.13.1                pypi_0    pypi
tblib                     3.0.0                    pypi_0    pypi
threadpoolctl             3.5.0                    pypi_0    pypi
thundersvm                0.3.4                    pypi_0    pypi
tk                        8.6.14               h0416ee5_0
toolz                     1.0.0                    pypi_0    pypi
tornado                   6.4.1           py312h827c3e9_0
tqdm                      4.66.5          py312hfc267ef_0
typing-extensions         4.12.2               hd8ed1ab_0    conda-forge
typing_extensions         4.12.2             pyha770c72_0    conda-forge
tzdata                    2024.1                   pypi_0    pypi
ucrt                      10.0.22621.0         h57928b3_1    conda-forge
urllib3                   2.2.3           py312haa95532_0
utf8proc                  2.6.1                h2bbff1b_1
vc                        14.40                h2eaa2aa_1
vc14_runtime              14.40.33810         hcc2c482_22    conda-forge
vs2015_runtime            14.40.33810         h3bf8584_22    conda-forge
wheel                     0.44.0          py312haa95532_0
win_inet_pton             1.1.0           py312haa95532_0
xyzservices               2022.9.0        py312haa95532_1
xz                        5.4.6                h8cc25b3_1
yaml                      0.2.5                he774522_0
zict                      3.0.0           py312haa95532_0
zipp                      3.20.2          py312haa95532_0
zlib                      1.2.13               h8cc25b3_1
zstd                      1.5.6                h8880b57_0

```

**Comment by xadrianzetx** [comment]
Looks like an issue with your local dask cluster setup. Make sure you are pointing the client at reachable cluster scheduler. See [dask docs](https://docs.dask.org/en/stable/deploying.html#local-machine).

**Comment by thegreatesthoneybee** [comment]
I came across dask for the first time today, so my understanding of the structure was lacking, thanks for your quick response :)

I found what the problem was.

First, when you create a LocalCluster, you need to explicitly define the scheduler_port.
Then I need to create a client with the local scheduler_port. 
Finally, we need to close the cluster and close with a try-finally statement.

Below is the modified example code with no errors.

```
import random
import time
import optuna
import optuna_distributed
from dask.distributed import Client, LocalCluster

def objective(trial):
    x = trial.suggest_float("x", -100, 100)
    y = trial.suggest_categorical("y", [-1, 0, 1])
    # Some expensive model fit happens here...
    time.sleep(random.uniform(1.0, 2.0))
    return x**2 + y

if __name__ == "__main__":
    cluster = LocalCluster(scheduler_port=8786)
    print(cluster)
    client = Client('127.0.0.1:8786')
    print(client)

    study = optuna_distributed.from_study(optuna.create_study(), client=client)
    
    try:
        study.optimize(objective, n_trials=10)
    finally:
        print(f"Best value: {study.best_value}")
        print(f"Best params: {study.best_params}")
        client.close()
        cluster.close()
```

**Comment by xadrianzetx** [comment]
Glad you found a solution :+1:
